### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by jhsu98** [ocavue/vuepress-theme-blogue#2]
I tried to follow your instructions but am receiving the error:

```
Extracting site metadata...ReferenceError: YOUR_PROJECT_PATH is not defined
    at Object.<anonymous> (/home/jonathan/blog/docs/.vuepress/config.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at resolveOptions (/home/jonathan/blog/node_modules/vuepress/lib/prepare.js:93:18)
    at prepare (/home/jonathan/blog/node_modules/vuepress/lib/prepare.js:24:25)
```

**Comment by jhsu98** [comment]
nevermind i figured this out.

**Comment by ocavue** [comment]
(๑>◡<๑) First user, yeah!

**Comment by ocavue** [comment]
Just updated the docs to avoid this question: 

https://github.com/ocavue/vuepress-theme-blogue/commit/ac9bcdf3dba386815202789ee6148ecef9b4eefd
